import { test, describe } from "node:test";
import assert from "node:assert/strict";
import { readFileSync, existsSync, statSync } from "node:fs";

/**
 * Phase 1 — PWA foundation.
 *
 * These assert the things a PWA audit used to score, since Lighthouse removed
 * its entire PWA category in v12 and there is now no automated proxy for
 * installability. Each rule here is one that silently breaks the app:
 *
 *   • the manifest must stay installable (icons, display, start_url, scope);
 *   • the worker must be generated by Serwist through the Turbopack route,
 *     because Next 16 builds with Turbopack and cannot run the webpack-based
 *     @serwist/next plugin at all;
 *   • nothing authenticated may reach Cache Storage — this app is multi-user
 *     and a cached dashboard document would survive logout;
 *   • zoom must stay enabled (WCAG 1.4.4).
 *
 * The caching rules are asserted against the source because the compiled
 * worker is only produced at request time. Comment stripping keeps prose from
 * satisfying a structural rule.
 */

const read = (p: string) => readFileSync(new URL(p, import.meta.url), "utf8");
const strip = (src: string) =>
  src.replace(/\/\*[\s\S]*?\*\//g, "").replace(/^[ \t]*\/\/.*$/gm, "");

interface ManifestIcon {
  src: string;
  sizes: string;
  type: string;
  purpose: string;
}
interface Manifest {
  id: string;
  name: string;
  short_name: string;
  start_url: string;
  scope: string;
  display: string;
  orientation?: string;
  theme_color: string;
  background_color: string;
  lang: string;
  icons: ManifestIcon[];
}
interface HeaderRule {
  source: string;
  headers: { key: string; value: string }[];
}
interface VercelConfig {
  headers: HeaderRule[];
  crons: { path: string; schedule: string }[];
}

const manifest = (): Manifest => JSON.parse(read("../public/manifest.json"));
const sw = () => strip(read("../app/sw.ts"));
const layout = () => strip(read("../app/layout.tsx"));
const vercel = (): VercelConfig => JSON.parse(read("../vercel.json"));

/**
 * Split the `runtimeCaching` array out of the worker source into one string
 * per entry, so a matcher can be asserted together with the handler that
 * actually belongs to it.
 */
function runtimeCachingEntries(src: string): string[] {
  const start = src.indexOf("const runtimeCaching = [");
  assert.notEqual(start, -1, "worker must declare a runtimeCaching array");
  const end = src.indexOf("\n];", start);
  assert.notEqual(end, -1, "runtimeCaching array is unterminated");
  const body = src.slice(start, end);
  return body
    .split(/\n\s*\{\s*\n/)
    .slice(1)
    .map((e) => e.replace(/\n\s*\},?\s*$/, ""))
    .filter((e) => e.trim().length > 0);
}

describe("web app manifest", () => {
  test("carries the fields Chrome requires for installability", () => {
    const m = manifest();
    assert.ok(m.name, "name");
    assert.ok(m.short_name, "short_name");
    assert.equal(m.start_url, "/dashboard");
    assert.equal(m.scope, "/");
    assert.equal(m.display, "standalone");
    assert.match(m.theme_color, /^#[0-9a-f]{3,8}$/i);
    assert.match(m.background_color, /^#[0-9a-f]{3,8}$/i);
  });

  test("ships 192 and 512 icons for both any and maskable purposes", () => {
    const { icons } = manifest();
    assert.ok(Array.isArray(icons) && icons.length > 0);
    for (const purpose of ["any", "maskable"]) {
      for (const size of ["192x192", "512x512"]) {
        const icon = icons.find((i) => i.sizes === size && i.purpose === purpose);
        assert.ok(icon, `missing ${size} ${purpose} icon`);
        assert.equal(icon.type, "image/png");
        assert.ok(icon.src.startsWith("/"), "icon src must be root-relative");
      }
    }
  });

  test("every declared icon exists on disk and is a real PNG of the declared size", () => {
    for (const icon of manifest().icons) {
      const path = new URL(`../public${icon.src}`, import.meta.url);
      assert.ok(existsSync(path), `missing file ${icon.src}`);
      // Real PNG signature, not an empty or HTML placeholder.
      const buf = readFileSync(path);
      assert.deepEqual(
        [...buf.subarray(0, 8)],
        [0x89, 0x50, 0x4e, 0x47, 0x0d, 0x0a, 0x1a, 0x0a],
        `${icon.src} is not a PNG`
      );
      // IHDR width/height live at a fixed offset in a PNG.
      const [w, h] = [buf.readUInt32BE(16), buf.readUInt32BE(20)];
      const declared = Number(icon.sizes.split("x")[0]);
      assert.equal(w, declared, `${icon.src} width`);
      assert.equal(h, declared, `${icon.src} height`);
      assert.ok(statSync(path).size > 0, `${icon.src} is empty`);
    }
  });

  test("is not locked to portrait, so desktop installs are not constrained", () => {
    // The admin dashboard is desktop-shaped; portrait-primary would letterbox
    // the installed window on a laptop.
    const m = manifest();
    assert.notEqual(m.orientation, "portrait-primary");
  });

  test("declares a stable id and language", () => {
    const m = manifest();
    assert.equal(m.id, "/dashboard");
    assert.equal(m.lang, "en");
  });
});

describe("serwist integration", () => {
  test("the hand-rolled worker is gone", () => {
    assert.equal(
      existsSync(new URL("../public/sw.js", import.meta.url)),
      false,
      "public/sw.js must be removed — app/sw.ts replaces it"
    );
  });

  test("the worker is built by Serwist through the Turbopack route handler", () => {
    const route = read("../app/serwist/[path]/route.ts");
    assert.match(route, /createSerwistRoute/, "must use createSerwistRoute");
    assert.match(route, /swSrc:\s*"app\/sw\.ts"/);
    // Next 16 defaults to Turbopack, which cannot run the webpack plugin.
    const config = read("../next.config.ts");
    assert.match(config, /withSerwist/, "next.config must wrap with withSerwist");
    assert.equal(
      existsSync(new URL("../node_modules/@serwist/turbopack", import.meta.url)),
      true,
      "@serwist/turbopack must be installed"
    );
  });

  test("registration happens through SerwistProvider, not a manual register()", () => {
    assert.match(layout(), /SerwistProvider/);
    assert.match(layout(), /swUrl="\/serwist\/sw\.js"/);
    // The old component registered the worker by hand; that path is retired.
    const bootstrap = read("../components/shared/pwa-bootstrap.tsx");
    assert.doesNotMatch(
      bootstrap,
      /serviceWorker\.register\(/,
      "registration belongs to SerwistProvider now"
    );
  });

  test("enables navigation preload and claims clients on activate", () => {
    const src = sw();
    assert.match(src, /navigationPreload:\s*true/);
    assert.match(src, /clientsClaim:\s*true/);
    assert.match(src, /skipWaiting:\s*true/);
  });

  test("precaches the offline fallback used when the network is unreachable", () => {
    const src = sw();
    assert.match(src, /url:\s*OFFLINE_URL/);
    assert.match(src, /destination === "document"/);
    // The fallback page has to exist as a real route.
    assert.ok(existsSync(new URL("../app/offline/page.tsx", import.meta.url)));
  });

  test("clears the cache left behind by the pre-Serwist worker", () => {
    const src = sw();
    assert.match(src, /taskora-v1/);
  });
});

describe("runtime caching never stores authenticated responses", () => {
  /**
   * The rule from the phase spec: cache GET data, never auth or mutations.
   *
   * Serwist's shipped defaultCache does NOT satisfy this — it NetworkFirst
   * caches same-origin HTML and RSC payloads for 24h. On a multi-user app that
   * puts a real session's dashboard page into Cache Storage where it survives
   * logout. So the worker must not use defaultCache, and every matcher must
   * leave auth traffic on the network.
   */
  test("does not fall back to Serwist's defaultCache", () => {
    const src = sw();
    assert.doesNotMatch(src, /runtimeCaching:\s*defaultCache/);
  });

  test("routes /api traffic to NetworkOnly", () => {
    // Split the runtimeCaching array into entries so each matcher is checked
    // together with its OWN handler. A substring search over the whole file is
    // not good enough: `!url.pathname.startsWith("/api/")` appears as a guard
    // inside an unrelated caching entry, so matching on the text alone would
    // happily pair the /api matcher with some other rule's handler.
    const entries = runtimeCachingEntries(sw());
    // Only entries that SELECT /api traffic. `!url.pathname.startsWith("/api/")`
    // is a guard that excludes /api from some other rule and is safe, so the
    // leading `!` must not count as a selection.
    const apiEntries = entries.filter((e) =>
      /(?<!!)url\.pathname\.startsWith\("\/api\/"\)/.test(e)
    );
    assert.ok(apiEntries.length > 0, "must have an explicit /api matcher");
    for (const entry of apiEntries) {
      assert.match(
        entry,
        /NetworkOnly/,
        `the /api matcher must resolve to NetworkOnly:\n${entry}`
      );
    }
  });

  test("routes RSC / prefetch payloads to NetworkOnly", () => {
    const entries = runtimeCachingEntries(sw());
    const rsc = entries.filter((e) => /RSC|Next-Router-Prefetch/.test(e));
    assert.ok(rsc.length > 0, "must detect RSC requests explicitly");
    for (const entry of rsc) {
      assert.match(entry, /NetworkOnly/, `RSC must be network only:\n${entry}`);
    }
  });

  test("serves navigations from a fallback without ever storing a document", () => {
    const entries = runtimeCachingEntries(sw());
    const docs = entries.filter((e) => /destination === "document"/.test(e));
    assert.ok(docs.length > 0, "documents must be matched explicitly");
    for (const entry of docs) {
      // The document route must not write to a cache. It either goes to the
      // network or reads the precached /offline page — nothing else. A
      // cache-writing strategy here would put authenticated HTML in storage.
      // (Matched on the constructor call, not a bare substring: the custom
      // handler's name contains "NetworkFirst" but it never caches.)
      assert.doesNotMatch(
        entry,
        /new (CacheFirst|StaleWhileRevalidate|CacheOnly)\(/,
        `documents must never be stored in a cache:\n${entry}`
      );
      assert.doesNotMatch(entry, /cacheName/, "no cache may be written for documents");
      assert.match(
        entry,
        /NetworkFirstWithOfflineFallback\(\)/,
        "documents must use the offline-fallback handler"
      );
    }
  });

  test("has a network-first navigation handler that falls back to /offline", () => {
    const src = sw();
    assert.match(src, /class NetworkFirstWithOfflineFallback extends NetworkOnly/);
    assert.match(src, /catch\s*\{[\s\S]*?caches\.open/);
    assert.match(src, /cache\.match\(OFFLINE_URL\)/);
    // A returned 503 guarantees the user sees something useful even if the
    // precache has not been populated yet.
    assert.match(src, /new Response\(/);
  });

  test("registers the document route before the catch-all deny rule", () => {
    // Workbox does not fall through to a later matching route when an earlier
    // one throws, so if the document rule sat below the catch-all the offline
    // fallback would never run. This ordering is load-bearing.
    const src = sw();
    const doc = src.indexOf("NetworkFirstWithOfflineFallback()");
    const catchAll = src.lastIndexOf("matcher: () => true");
    assert.notEqual(doc, -1);
    assert.notEqual(catchAll, -1);
    assert.ok(doc < catchAll, "the document route must be registered first");
  });

  test("ends with a catch-all NetworkOnly so nothing unlisted is ever cached", () => {
    const entries = runtimeCachingEntries(sw());
    const catchAll = entries.find((e) => /matcher:\s*\(\)\s*=>\s*true/.test(e));
    assert.ok(catchAll, "needs a catch-all entry");
    assert.match(catchAll, /NetworkOnly/, "the catch-all must be network only");
    // And it must be the final entry, so nothing is evaluated after it.
    assert.equal(
      entries[entries.length - 1].trim(),
      catchAll.trim(),
      "the catch-all must be last"
    );
  });

  test("every caching entry is scoped to static assets, never a bare catch-all", () => {
    // A caching entry whose matcher has no same-origin guard and no
    // asset-only extension regex could cache a third-party response — which on
    // this app would include Supabase API traffic.
    for (const entry of runtimeCachingEntries(sw())) {
      const caches = /new (CacheFirst|StaleWhileRevalidate|NetworkFirst|CacheOnly)\(/.test(
        entry
      );
      if (!caches) continue;
      const scoped =
        /sameOrigin/.test(entry) ||
        /\(\?:eot\|otf/.test(entry) ||
        /\(\?:png\|jpe\?g/.test(entry);
      assert.ok(
        scoped,
        `caching entry is not scoped to same-origin static assets:\n${entry}`
      );
    }
  });
});

describe("service worker response headers", () => {
  test("vercel.json sets no-store-style caching and scope for the worker", () => {
    const headers = vercel().headers;
    const swRule = headers.find((h) => h.source === "/serwist/:path*");
    assert.ok(swRule, "missing /serwist/:path* headers rule");
    const map = Object.fromEntries(
      swRule.headers.map((h) => [h.key.toLowerCase(), h.value])
    );
    // must-revalidate is what makes a new worker actually be picked up.
    assert.match(map["cache-control"] ?? "", /must-revalidate/);
    assert.equal(map["service-worker-allowed"], "/");
  });

  test("the generated route already scopes the worker to the whole origin", () => {
    // The worker lives at /serwist/sw.js, so without this header it could
    // only control /serwist/* and the app would never be offline-capable.
    const route = read("../app/serwist/[path]/route.ts");
    assert.ok(route.length > 0);
    assert.match(
      read("../vercel.json"),
      /"Service-Worker-Allowed"/
    );
  });

  test("icons are cached long-term and the manifest is revalidated", () => {
    const headers = vercel().headers;
    const icons = headers.find((h) => h.source === "/icons/:path*");
    assert.ok(icons, "missing /icons/:path* headers rule");
    assert.match(
      Object.fromEntries(icons.headers.map((h) => [h.key.toLowerCase(), h.value]))[
        "cache-control"
      ],
      /immutable/
    );
    const mf = headers.find((h) => h.source === "/manifest.json");
    assert.ok(mf, "missing manifest headers rule");
  });

  test("the cron schedule is preserved", () => {
    const cron = vercel().crons.find((c) => c.path === "/api/cron/daily-reminders");
    assert.ok(cron, "the daily-reminders cron must survive the header changes");
    assert.equal(cron.schedule, "0 5 * * *");
  });
});

describe("install and update UX", () => {
  test("viewport does not disable pinch-zoom (WCAG 1.4.4)", () => {
    const src = layout();
    assert.doesNotMatch(src, /maximumScale/, "maximumScale disables zoom");
    assert.doesNotMatch(src, /userScalable/);
    // The safe-area behaviour the install prompt depends on is retained.
    assert.match(src, /viewportFit:\s*"cover"/);
    assert.match(src, /initialScale:\s*1/);
  });

  test("offers an update toast when a new worker is waiting", () => {
    const src = strip(read("../components/shared/pwa-bootstrap.tsx"));
    assert.match(src, /useSerwist\(\)/);
    assert.match(src, /addEventListener\("waiting"/);
    assert.match(src, /window\.location\.reload\(\)/);
  });

  test("offers iOS Add-to-Home-Screen guidance, which Safari cannot prompt for", () => {
    const src = strip(read("../components/shared/pwa-bootstrap.tsx"));
    assert.match(src, /iphone\|ipad\|ipod/i, "must detect iOS");
    assert.match(src, /Add to Home Screen/);
    // Already-installed users must not be nagged.
    assert.match(src, /display-mode:\s*standalone/);
  });

  test("still honours the install-dismiss cooldown", () => {
    const src = read("../components/shared/pwa-bootstrap.tsx");
    assert.match(src, /DISMISS_KEY/);
    assert.match(src, /DISMISS_DURATION/);
  });
});

describe("app shell", () => {
  test("has a branded not-found page", () => {
    assert.ok(existsSync(new URL("../app/not-found.tsx", import.meta.url)));
  });
});